### ISSUE TITLE
Запрос на изменение дизайна

### ISSUE THREAD

**Issue by searchency** [Attvud/SDS#1]
добавить в время доставки возможность добавить несколько интервалов времени, например с 10 до 12   и второй с 17 до 19  можно больше интервалов времени. Реализовать предлагаю просто добавлением плюсика и появляется новое поле TIME1 TIME2 TIME3 и т д.

**Comment by searchency** [comment]
ну и плюс меняется на минус чтобы этот интервал удалить или редактировать

**Comment by Attvud** [comment]
Правка внесена.

Видео отчет (смотреть обязательно) - https://youtu.be/LsJso-Zj_GU. 
Это видео также добавлено в [общий видео плейлист проекта](https://www.youtube.com/playlist?list=PLqvLEn6IhFsCC1TVRLxnWuQ3dqs-TbDMW):

![Снимок экрана 2020-06-30 в 1 16 08](https://user-images.githubusercontent.com/32170181/86061369-58130880-ba6f-11ea-86c2-1c2a80974fc2.png)

Везде, где были два поля время и дата, стало одно поле. Например на экране информации о заказе:

![Снимок экрана 2020-06-30 в 1 10 35](https://user-images.githubusercontent.com/32170181/86060977-83492800-ba6e-11ea-909f-a5e7b1994a0d.png).
